// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: service.proto
package handlers

import (
	context "context"

	api "gitlab.myteksi.net/dakota/fun-with-go/api"
	v2 "gitlab.myteksi.net/dakota/servus/v2"
)

// RegisterRoutes registers handlers with the Servus library.
func (f *FunWithGoService) RegisterRoutes(app *v2.Application) {
	app.POST(
		"/api/v1/example",
		func(ctx context.Context, req interface{}) (interface{}, error) {
			res, err := f.Example(ctx, req.(*api.Request))
			return res, err
		},
		v2.WithRequest(&api.Request{}),
		v2.WithResponse(&api.Response{}),
	)
}
