// Code generated by protoc-gen-go-svc. DO NOT EDIT.
// source: service.proto
package api

import (
	context "context"
)

// Request is an example request.
type Request struct {
	Value string `json:"value,omitempty"`
}

// Response is an example response.
type Response struct {
	Value string `json:"value,omitempty"`
}

// FunWithGo <TODO: add a short description here>
type FunWithGo interface {
	Example(ctx context.Context, req *Request) (*Response, error)
}
